version: "3.9"

services:
  swagger-editor:
    image: swaggerapi/swagger-editor:v4.12.1
    ports:
      - "8085:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui:v5.11.8
    ports:
      - "8086:8080"
    volumes:
      - ./docs/api:/usr/share/nginx/html/docs
    environment:
#      SWAGGER_JSON: /usr/share/nginx/html/docs/apidocs.swagger.json
      URLS: "[
        {url: '/docs/app/v1/service.swagger.json', name: 'API version 1'}
      ]"

  postgres:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - "3333:8080"
    depends_on:
      - postgres

  redis:
    image: redis/redis-stack:7.2.0-v9
    ports:
      - "6379:6379"
      - "8087:8001"
    volumes:
      - redis_volume:/data

volumes:
  postgres_volume:
  redis_volume:
