version: "3.9"

services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor-container"
    ports:
      - "8085:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui-container"
    ports:
      - "8086:8080"
    volumes:
      - ./docs/microservice:/usr/share/nginx/html/docs
    environment:
      URLS: "[
        {url: '/docs/v1/microservice_grpc.swagger.json', name: 'API Version 1.0'}
      ]"
