app:
  env: "local"

logger:
  level: debug
  add-source: true
  json: false

grpc:
  host: "localhost"
  port: 50051

rest:
  host: "localhost"
  port: 8080
  timeout:
    read: 5s
    write: 5s
    idle: 15s
  cors:
    origin: "*"
    max-age: 0

swagger:
  editor:
    port: 8085
  ui:
    port: 8086

postgres:
  host: "localhost"
  port: 5432
  # Set env
  # user:
  # password:
  # database:
  sslmode: disable

adminer:
  port: 3333
