app:
  env: "local"

logger:
  level: debug
  add-source: true
  json: false

# openssl rand -base64 48
jwt:
  secret: OHgnU3V9vLvaGe+6USuxhHaXswyy6eK2YxGgAPnFscdndPy+dyJc6zXLL6WzD+yz
  expires: 3600

grpc:
  host: "localhost"
  port: 50051

rest:
  host: "localhost"
  port: 8080
  timeout:
    read: 5s
    write: 5s
    idle: 15s
  cors:
    origin: "*"
    max-age: 0

postgres:
  host: "localhost"
  # Set env
  # port:
  # user:
  # password:
  # database:
  sslmode: disable
  is-migration: false
